[project]
name = "vision-artificial"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "DevAvirama", email = "santyaviramagnf@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "numpy>=2.5.2",
    "opencv-python>=5.0.0.93",
    "ultralytics>=8.4.120",
]

[project.scripts]
vision-artificial = "vision_artificial:main"

[build-system]
requires = ["uv_build>=0.12.3,<0.13.0"]
build-backend = "uv_build"
